# Generated by Django 5.1.7 on 2025-03-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.custom_usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('product_type', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.categoriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.categoriesmodel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeModel',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalProductModel',
            fields=[
                ('digital_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=2000)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantModel',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='product_image')),
                ('image2', models.ImageField(upload_to='product_image')),
                ('image3', models.ImageField(upload_to='product_image')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.productmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.custom_usermodel')),
            ],
        ),
    ]
