# Generated by Django 5.1.7 on 2025-03-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_paymentsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='stock',
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.categoriesmodel'),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='discount_per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
