# Generated by Django 5.1.7 on 2025-03-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_remove_productmodel_price_remove_productmodel_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='sub_category',
            new_name='parent_category',
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='image1',
            field=models.ImageField(upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='image2',
            field=models.ImageField(upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='image3',
            field=models.ImageField(upload_to='product_image/'),
        ),
    ]
