# Generated by Django 5.1.7 on 2025-03-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_rename_sub_category_categoriesmodel_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
