# Generated by Django 5.1.7 on 2025-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_productvariantmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='best_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='trending_product',
            field=models.BooleanField(default=True),
        ),
    ]
