# Generated by Django 5.1.7 on 2025-05-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_productmodel_trending_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='coreapp.productmodel'),
        ),
    ]
