# Generated by Django 5.1.7 on 2025-05-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_alter_productvariantmodel_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='coreapp.categoriesmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coreapp.categoriesmodel'),
        ),
    ]
