# Generated by Django 5.1.7 on 2025-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_alter_categoriesmodel_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributemodel',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
