# Generated by Django 5.1.7 on 2025-05-13 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_productattributemodel_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributemodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productattributemodel',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productattributemodel',
            name='variant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.productvariantmodel'),
        ),
    ]
