# Generated by Django 5.1.7 on 2025-05-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_remove_productattributemodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributemodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.productmodel'),
        ),
    ]
