# Generated by Django 5.1.7 on 2025-05-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_productattributemodel_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
