# Generated by Django 5.1.7 on 2025-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_delete_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsmodel',
            name='payment_mode',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('COD', 'Cash on Delivery'), ('UPI', 'UPI')], default='Razorpay', max_length=50),
        ),
    ]
