# Generated by Django 5.1.7 on 2025-05-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_paymentsmodel_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmodel',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_image/'),
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='review',
            field=models.TextField(max_length=1000),
        ),
    ]
