# Generated by Django 5.1.7 on 2025-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
