# Generated by Django 5.1.7 on 2025-05-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_remove_cartmodel_id_alter_cartmodel_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cartapp.cartmodel'),
        ),
    ]
