# Generated by Django 5.1.7 on 2025-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_alter_cartitemmodel_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='selected_attribute_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
