# Generated by Django 5.1.7 on 2025-03-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='order_item',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='orderapp.orderitemmodel'),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
