# Generated by Django 5.1.7 on 2025-03-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_orderitemmodel_ordered_ordersmodel_order_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
