# Generated by Django 5.1.7 on 2025-03-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_rename_quatity_orderitemmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='order_id',
        ),
    ]
