# Generated by Django 5.1.7 on 2025-05-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_remove_orderitemmodel_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='order_item',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='order_items',
            field=models.ManyToManyField(to='orderapp.orderitemmodel'),
        ),
    ]
